# This file may be used to create an environment using:
# $ conda create --name <env> --file <this file>
# platform: linux-64
# created-by: conda 25.9.1
_openmp_mutex=4.5=20_gnu
accelerate=1.12.0=pypi_0
aiohappyeyeballs=2.6.1=pypi_0
aiohttp=3.13.3=pypi_0
aiosignal=1.4.0=pypi_0
annotated-types=0.7.0=pypi_0
anthropic=0.49.0=pypi_0
anyio=4.12.1=pypi_0
async-timeout=5.0.1=pypi_0
attrs=25.4.0=pypi_0
av=16.1.0=pypi_0
bzip2=1.0.8=hda65f42_9
ca-certificates=2026.1.4=hbd8a1cb_0
cachetools=7.0.1=pypi_0
certifi=2026.1.4=pypi_0
cffi=2.0.0=pypi_0
charset-normalizer=3.4.4=pypi_0
cryptography=46.0.5=pypi_0
cuda-bindings=12.9.4=pypi_0
cuda-pathfinder=1.3.5=pypi_0
cycler=0.12.1=pypi_0
descartes=1.1.0=pypi_0
distro=1.9.0=pypi_0
einops=0.8.1=pypi_0
exceptiongroup=1.3.1=pypi_0
filelock=3.24.3=pypi_0
fire=0.7.0=pypi_0
fonttools=4.61.1=pypi_0
frozenlist=1.8.0=pypi_0
fsspec=2026.2.0=pypi_0
google-ai-generativelanguage=0.6.15=pypi_0
google-api-core=2.30.0=pypi_0
google-api-python-client=2.190.0=pypi_0
google-auth=2.49.0.dev0=pypi_0
google-auth-httplib2=0.3.0=pypi_0
google-generativeai=0.8.4=pypi_0
googleapis-common-protos=1.72.0=pypi_0
grpcio=1.78.1=pypi_0
grpcio-status=1.71.2=pypi_0
h11=0.16.0=pypi_0
httpcore=1.0.9=pypi_0
httplib2=0.31.2=pypi_0
httpx=0.28.1=pypi_0
huggingface-hub=0.29.3=pypi_0
icu=78.2=h33c6efd_0
idna=3.11=pypi_0
jinja2=3.1.6=pypi_0
jiter=0.13.0=pypi_0
joblib=1.4.2=pypi_0
kiwisolver=1.4.9=pypi_0
ld_impl_linux-64=2.45.1=default_hbd61a6d_101
libexpat=2.7.4=hecca717_0
libffi=3.5.2=h3435931_0
libgcc=15.2.0=he0feb66_18
libgcc-ng=15.2.0=h69a702a_18
libgomp=15.2.0=he0feb66_18
liblzma=5.8.2=hb03c661_0
libnsl=2.0.1=hb9d3cd8_1
libsqlite=3.51.2=hf4e2dac_0
libstdcxx=15.2.0=h934c35e_18
libuuid=2.41.3=h5347b49_0
libxcrypt=4.4.36=hd590300_1
libzlib=1.3.1=hb9d3cd8_2
markupsafe=3.0.3=pypi_0
matplotlib=3.5.3=pypi_0
mpmath=1.3.0=pypi_0
multidict=6.7.1=pypi_0
ncurses=6.5=h2d0b736_3
networkx=3.4.2=pypi_0
numpy=1.26.4=pypi_0
nuscenes-devkit=1.1.11=pypi_0
nvidia-cublas-cu12=12.1.3.1=pypi_0
nvidia-cuda-cupti-cu12=12.1.105=pypi_0
nvidia-cuda-nvrtc-cu12=12.1.105=pypi_0
nvidia-cuda-runtime-cu12=12.1.105=pypi_0
nvidia-cudnn-cu12=9.1.0.70=pypi_0
nvidia-cufft-cu12=11.0.2.54=pypi_0
nvidia-cufile-cu12=1.14.1.1=pypi_0
nvidia-curand-cu12=10.3.2.106=pypi_0
nvidia-cusolver-cu12=11.4.5.107=pypi_0
nvidia-cusparse-cu12=12.1.0.106=pypi_0
nvidia-cusparselt-cu12=0.7.1=pypi_0
nvidia-nccl-cu12=2.21.5=pypi_0
nvidia-nvjitlink-cu12=12.9.86=pypi_0
nvidia-nvshmem-cu12=3.4.5=pypi_0
nvidia-nvtx-cu12=12.1.105=pypi_0
openai=0.28.0=pypi_0
opencv-python=4.11.0.86=pypi_0
openssl=3.6.1=h35e630c_1
packaging=26.0=pyhcf101f3_0
pandas=2.2.3=pypi_0
pillow=11.1.0=pypi_0
pip=26.0.1=pyh8b19718_0
propcache=0.4.1=pypi_0
proto-plus=1.27.1=pypi_0
protobuf=5.29.6=pypi_0
psutil=5.9.0=pypi_0
pyasn1=0.6.2=pypi_0
pyasn1-modules=0.4.2=pypi_0
pycocotools=2.0.8=pypi_0
pycparser=3.0=pypi_0
pydantic=2.12.5=pypi_0
pydantic-core=2.41.5=pypi_0
pyparsing=3.3.2=pypi_0
pyquaternion=0.9.9=pypi_0
python=3.10.19=h3c07f61_3_cpython
python-dateutil=2.9.0.post0=pypi_0
pytz=2025.2=pypi_0
pyyaml=6.0.2=pypi_0
qwen-vl-utils=0.0.10=pypi_0
readline=8.3=h853b02a_0
regex=2026.2.19=pypi_0
requests=2.32.5=pypi_0
safetensors=0.7.0=pypi_0
scikit-learn=1.6.1=pypi_0
scipy=1.15.2=pypi_0
setuptools=82.0.0=pyh332efcf_0
shapely=1.8.5=pypi_0
six=1.17.0=pypi_0
sniffio=1.3.1=pypi_0
sympy=1.13.1=pypi_0
tabulate=0.9.0=pypi_0
termcolor=3.3.0=pypi_0
threadpoolctl=3.6.0=pypi_0
timm=1.0.15=pypi_0
tk=8.6.13=noxft_h366c992_103
tokenizers=0.21.1=pypi_0
torch=2.5.1+cu121=pypi_0
torchaudio=2.5.1+cu121=pypi_0
torchvision=0.20.1+cu121=pypi_0
tqdm=4.67.1=pypi_0
transformers=4.49.0=pypi_0
triton=3.1.0=pypi_0
typing-extensions=4.15.0=pypi_0
typing-inspection=0.4.2=pypi_0
tzdata=2025.3=pypi_0
uritemplate=4.2.0=pypi_0
urllib3=2.6.3=pypi_0
wheel=0.46.3=pyhd8ed1ab_0
yarl=1.22.0=pypi_0
zstd=1.5.7=hb78ec9c_6
